name: izipay_payment
description: "A plugin for integrating izipay payment gateway in flutter"
version: 1.0.0
maintainer: Carlos EspaÃ±a (@creegplay)
homepage: https://github.com/carlinsk8/izipay_payment
repository: https://github.com/carlinsk8/izipay_payment
issue_tracker: https://github.com/carlinsk8/izipay_payment/issues

environment:
  sdk: ^3.5.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.izipay.payment.izipay_payment
        pluginClass: IzipayPaymentPlugin
      ios:
        pluginClass: IzipayPaymentPlugin